version: 2.1
orbs:
  gcloud:  travelaudience/gcloud@0.1.1

workflows:
  cost-estimation:
    jobs:
      - cost_estimation:
          context:
            - credentials
          filters:
            branches:
              only:
                - master
                - dev
jobs:
  cost_estimation:
    docker:
      - image: $USERNAME/k8s-cost-estimator:v0.0.2
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: Cost estimation 
          command: |
            set -e

            # Donload manifests from the repo into 'previous' folder. Checkot in master branch because  
            # at the current moment the latest code is in master. 
            echo ""
            echo "*************************************************************************"
            echo "** Checking out 'master' branch ..."
            echo "*************************************************************************"
            git config --global user.email "dmytro.pakki@standardindustries.com" && git config --global user.name "dpakki"
            mkdir previous
            git clone https://github.com/dpakki/k8s-cost-estimator-github.git previous/
            cd previous
            git checkout master
            cd ..

            # Compare the code from 'prvious' folder with the current one. --k8s - where manifests are situated
            echo ""
            echo "*************************************************************************"
            echo "** Estimating cost difference between current and previous versions..."
            echo "*************************************************************************"
            echo $TECHSTACK_EDITOR > sa-key.json
            k8s-cost-estimator --k8s wordpress --k8s-prev previous/wordpress --output output.json --environ=GITHUB --auth-key sa-key.json

            echo ""
            echo "***************************************************************************************************************"
            echo "** Updating Pull Request ${CIRCLE_PULL_REQUEST##*/} ..."
            echo "***************************************************************************************************************"
            createObject() {
              url=$1
              body=$2

              echo $url
              echo $body
              echo "Request Start"
              resp=$(curl -w "\nSTATUS_CODE:%{http_code}\n" -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $GITHUB_TOKEN" -d "$body"  "$url")
              echo $resp
              
              # httpStatusCode=$([[ $resp =~ [[:space:]]*STATUS_CODE:([0-9]{3}) ]] && echo ${BASH_REMATCH[1]})
              # if [ $$httpStatusCode != "201" ] 
              #   then
              #     echo "Error creating object!"
              #     echo "\- URL: $url "
              #     echo "\- BODY: $body "
              #     echo "\- RESPONSE: $resp "
              #     exit -1
              # fi
            }

            comments_url="https://api.github.com/repos/dpakki/k8s-cost-estimator-github/issues/${CIRCLE_PULL_REQUEST##*/}/comments"
            comments_body="$(cat output.json)"
            createObject $comments_url "$comments_body"

          #   COST_USD_THRESHOLD=$_GITHUB_FINOPS_COST_USD_THRESHOLD
          #   POSSIBLY_COST_INCREASE=$(cat output.diff | jq ".summary.maxDiff.usd")
          #   if (( $(echo "$$POSSIBLY_COST_INCREASE > $$COST_USD_THRESHOLD" | bc -l) ))
          #     then
          #       echo ""
          #       echo "****************************************************************************************"
          #       echo "** Possible cost increase bigger than \$ $$COST_USD_THRESHOLD USD detected. Requesting FinOps approval ..."
          #       echo "****************************************************************************************"   
          #       reviewers_url="https://api.github.com/repos/GITHUB_USER/k8s-cost-estimator-github/pulls/$_PR_NUMBER/requested_reviewers"
          #       reviewers_body="{\"reviewers\":[\"$_GITHUB_FINOPS_REVIEWER_USER\"]}"
          #       createObject $$reviewers_url "$$reviewers_body"
          #     else
          #       echo ""
          #       echo "****************************************************************************************************************"
          #       echo "** No cost increase bigger than \$ $$COST_USD_THRESHOLD USD detected. FinOps approval is NOT required in this situation!"
          #       echo "****************************************************************************************************************"
          #   fi